name = "Fume"
author = "Blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1537f8d648519e9071e77543d621eb1ad6ec4e78db954bc250e014aa8d013d4c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
