name = "fumosoPack"
author = "blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "391e4c60505225d34ad8cfcd5f782b62ffebd220546dd7c6e64edeaf9d3bd458"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
