name = "Fume"
author = "Blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1210f3460892c385f4b9a7ea5a49321ab0d59b3d9b3389583b9e420076b665a7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
