name = "fumosoPack"
author = "blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9e77344e236ee1a947379302934a74dfe323cf125baee9af4cc21d17ebabde4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
