name = "fumosoPack"
author = "blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de6f88cae320262e416c94dcd7f07f16791b3921f46966e566f0a5d3bf95a0ee"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
