name        = "fumosoPack"
author      = "blasg"
version     = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
type                  = "direct"
url                   = "https://blasg2.github.io/FumeRepo/index.toml"
download_url_template = "https://cdn.jsdelivr.net/gh/Blasg222/FumeRepo@main/mods/{{name}}"

[versions]
forge       = "47.4.0"
minecraft   = "1.20.1"
