name = "FumePack"
author = "Guiso"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ee602359acf08b500d056cb11c27d9b92b53067c3ea1b36e5005e108d1a93da"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
