name = "fumosoPack"
author = "blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b47130fb636e272945650f581babf52dbcc20f93d7bd37c34bf31eaebd94d66"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
