name = "Fume"
author = "Blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "018b14a1d665cde47efd40b7a42a434fd737ce13c689604687b00aaccc59cedf"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
