name = "fumosoPack"
author = "blasg"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53feaf64c92e680f753bd71a3776cf3a694519ffc8ee8cd00b6b4b7b6f6ecd4f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
