name = "Fume"
author = "Blasg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cdf0f128c4f6afc99fe93aa4e937cd4f0668e6c10aeb634fcce9fb99061f508"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
