drop_none_applicable_widget = true
enable_pop_up = true
#Range: 1 ~ 200
popup_interval = 5
#Range: 4 ~ 48
popup_distance = 16
popup_all_nearby_entity = true
popup_all_nearby_block = true
transform_context_after_mob_conversation = true
#Range: 0.1 ~ 16.0
render_max_distance = 8.0
#Range: 0.1 ~ 16.0
render_min_distance = 1.0
#measured in tick
#Range: 1 ~ 1200
display_after_not_seen = 80
#Range: 0.1 ~ 2.5
global_hologram_range = 0.29999999999999993
skip_hologram_if_empty = true
display_interactive_hint = true
render_debug_layer = false
render_debug_hologram_life_cycle_box = false
render_widget_debug_info = false
render_network_debug_info = false
render_debug_transient_target = false
render_interact_transient_re_mapping_indicator = false
#Allowed Values: DEFAULT, REI, JEI, AUTO
search_backend = "AUTO"

