#Allowed Values: TEXT, SCREEN_NO_BACKGROUND, SCREEN_BACKGROUND
item_tooltip_type = "SCREEN_NO_BACKGROUND"
render_interact_indicator = true
#Range: 1 ~ 20
interact_indicator_distance = 8
#Range: 0.001 ~ 0.999
interact_indicator_percent = 0.2
#Range: 0 ~ 255
widget_background_alpha = 127

